esphome:
  name: chicken-coop

esp8266:
  board: thingdev

# TODO disable
logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  domain: ""
  ap:
    ssid: chicken-coop-ap

captive_portal:

mdns:
  disabled: true

# TODO disable
web_server:

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 5s # TODO "never"
