substitutions:
  node_id: 'x'

esphome:
  name: "hx711-scale-${node_id}"

esp8266:
  board: d1_mini

# Enable logging
# logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  domain: ""
  ap:
    ssid: "hx711-scale-${node_id}-cp"

mdns:
  disabled: true

captive_portal:

web_server:

prometheus:

sensor:
  - platform: hx711
    name: hx711_value
    dout_pin: D7
    clk_pin: D5
    filters:
#      - calibrate_linear: # hx711-scale-1
#          - -598000 -> 0
#          - -899000 -> 40
#          - -1304000 -> 80
#          - -1718000 -> 120
      - calibrate_linear: # hx711-scale-2
          - -144260 -> 0
          - -543083 -> 40
          - -933303 -> 80
          - -1721922 -> 120
    unit_of_measurement: lb
