esphome:
  name: propane-tank-monitor

esp8266:
  board: thingdev

# TODO disable
logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  domain: ""
  ap:
    ssid: propane-tank-monitor-ap

captive_portal:

mdns:
  disabled: true

# TODO disable
web_server:

i2c:
  scan: false
  sda: GPIO2
  scl: GPIO14

ads1115:
  - address: 0x48 # ADDR pulled to GND

sensor:
  - platform: ads1115
    name: VIN
    multiplexer: A0_GND
    gain: 4.096
    update_interval: 5s # TODO "never"
    filters:
      - multiply: 1.99
      - offset: 0.0753
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 5s # TODO "never"
