esphome:
  name: propane-tank-monitor

esp8266:
  board: thingdev

# TODO disable
logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  domain: ""
  ap:
    ssid: propane-tank-monitor-ap

captive_portal:

mdns:
  disabled: true

# TODO disable
web_server:

i2c:
  scan: false
  sda: GPIO2
  scl: GPIO14

ads1115:
  - address: 0x48 # ADDR pulled to GND

# TODO do VDD pins need to be programmatically enabled?

sensor:
  - platform: ads1115
    id: a0_raw
    multiplexer: A0_GND
    gain: 4.096
    update_interval: 5s # TODO "never"
  - platform: copy
    source_id: a0_raw
    name: VIN
    filters:
      - calibrate_linear:
          # 1.99 * x + 0.0753
          datapoints:
            - 2.225 -> 4.5
            - 2.176 -> 4.4
            - 2.126 -> 4.3
            - 2.073 -> 4.2
            - 2.025 -> 4.1
            - 1.974 -> 4.0
            - 1.925 -> 3.9
            - 1.874 -> 3.8
            - 1.823 -> 3.7
            - 1.773 -> 3.6
            - 1.723 -> 3.5
            - 1.673 -> 3.4
            - 1.621 -> 3.3
  - platform: ads1115
    id: a1_raw
    multiplexer: A1_GND
    gain: 2.048
    update_interval: 1s # TODO "never"
  - platform: copy
    source_id: a1_raw
    filters:
      - calibrate_polynomial:
          # 100 * x^3 - 514 * x^2 + 880x - 502
          degree: 3
          datapoints:
            - 1.608 -> 0.05
            - 1.590 -> 0.10
            - 1.594 -> 0.20
            - 1.622 -> 0.30
            - 1.658 -> 0.40
            - 1.703 -> 0.50
            - 1.746 -> 0.60
            - 1.784 -> 0.70
            - 1.813 -> 0.80
            - 1.823 -> 0.90
            - 1.811 -> 0.95
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 5s # TODO "never"
